Helps 4372 vs code webform redesign
open-olive/loop-creator-vscode pull request #79
Opened 2022-06-09 00:53 UTC by oelumezeolive

## [HELPS-4372](https://crosschx.atlassian.net/browse/HELPS-4372)

### Changes made:

- Re-Creation of create-loop form that shows up in the webview of vscode.
- Separation of logic on the create form page, for js files that will be loaded.

### Additional notes:
[link to Figma Design for new form](https://www.figma.com/file/cAwljjbVtikJK7v1Dm9D60/VS-Code?node-id=0%3A1)
<img width="1332" alt="Screen Shot 2022-06-08 at 7 51 53 PM" src="https://user-images.githubusercontent.com/99768387/172741486-f23e6a63-a4ab-4305-a164-d05115833933.png">

2022-06-09 20:25 UTC, ulricesparra-oliveai requested changes

2022-06-09 20:25 UTC, ulricesparra-oliveai commented on src/loopCreator.ts
> +    // htmlView = htmlView.replace("{{oliveLogoPath}}", oliveLogoDiskPath.toString());
Was this intentional? Looks like `oliveLogoPath` isn't being used anywhere else so I'm assuming this wasn't intended

2022-06-09 21:17 UTC, aleciberg-olive approved these changes

2022-06-13 18:16 UTC, ulricesparra-oliveai approved these changes

2022-06-14 18:09 UTC, merged